categories:
- InteractiveTools
description: Chat with your dataset powered by LLMs
name: chatanalysis
owner: goeckslab
remote_repository_url: https://github.com/goeckslab/ChatAnalysis
include:
  - chat_analysis.xml
  - README.md
  - test-data/*
  